### ISSUE TITLE
Travis not passing due to LibSSH2 dependency

### ISSUE THREAD

**Issue by terrytangyuan** [terrytangyuan/lfda#12]
@zachmayer Would you be able to take a look at this? I tried several ways to install but still not passing. Similar to rgl dependency problem. How did you get managed to pass it?

**Comment by zachmayer** [comment]
This is the actual warning that's causing your build to fail:

``` bash
* checking CRAN incoming feasibility ... WARNING
Maintainer: ‘Yuan Tang <terrytangyuan@gmail.com>’
Insufficient package version (submitted: 1.0.0, existing: 1.0.0)
Days since last update: 0
License components with restrictions and base license permitting such:
  MIT + file LICENSE
File 'LICENSE':
  YEAR: 2015
  COPYRIGHT HOLDER: Yuan Tang
```

Basically, this is saying if you submitted to CRAN as-is, they'd reject it because 1.0.0 is already on CRAN. Just bump the version number, and it should go away.

**Comment by zachmayer** [comment]
The libcurl note isn't even a NOTE or WARNING:

``` bash
Checking URLs requires 'libcurl' support in the R build
```

It looks like the travis team is working on that.  Hopefully it will be fixed in the near future, but it's not a big deal for now:
https://github.com/travis-ci/travis-ci/issues/3970
https://github.com/PredictiveEcology/SpaDES/issues/192
