### ISSUE TITLE
JOSS Review Tests

### ISSUE THREAD

**Issue by sctyner** [terrytangyuan/lfda#23]
Again for the JOSS [review](https://github.com/openjournals/joss-reviews/issues/1572). There are six empty tests (i.e. they are not testing anything):

- In [test_helper_functions.R](https://github.com/terrytangyuan/lfda/blob/master/tests/testthat/test_helper_functions.R)
    - "kmatrixGauss function works"
    - "repmat works" 
- In [test_klfda.R](https://github.com/terrytangyuan/lfda/blob/master/tests/testthat/test_klfda.R)
    - "klfda works" 
- In [test_visualization.R](https://github.com/terrytangyuan/lfda/blob/master/tests/testthat/test_visualization.R)
    - "klfda visualization works"
    - "lfda visualization works"
    - "self visualization works"

**Comment by terrytangyuan** [comment]
What do you mean? They are testing the exposed functions from the package.

**Comment by sctyner** [comment]
They do not contain any expectations. From the `test_that()` [documentation](https://testthat.r-lib.org/reference/test_that.html), there are 2 arguments to `test_that()`: `desc` and `code`. `desc` is the "test name. Names should be kept as brief as possible, as they are often used as line prefixes." `code` is "test code containing expectations."

Here is the output from `devtools::test()`:

```r
> devtools::test()
Loading lfda
Testing lfda
✔ |  OK F W S | Context
✔ |   1     2 | helper functions
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
test_helper_functions.R:5: skip: kmatrixGauss function works
Empty test

test_helper_functions.R:9: skip: repmat works
Empty test
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔ |   0     1 | klfda
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
test_klfda.R:5: skip: klfda works
Empty test
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔ |   3       | lfda
✔ |   3       | self [0.4 s]
✔ |   5     3 | visualization [0.2 s]
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
test_visualization.R:5: skip: klfda visualization works
Empty test

test_visualization.R:16: skip: lfda visualization works
Empty test

test_visualization.R:27: skip: self visualization works
Empty test
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

══ Results ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 0.7 s

OK:       12
Failed:   0
Warnings: 0
Skipped:  6
```

**Comment by terrytangyuan** [comment]
This has been fixed:
```
> devtools::test(".")
Loading lfda
Testing lfda
✔ | OK F W S | Context
✔ |  4       | Test the helper functions used in lfda implementations
✔ |  6       | Test klfda functionalities [0.1 s]
✔ | 13       | Test lfda functionalities [0.1 s]
✔ |  9       | self [0.5 s]
✔ |  8       | Test visualization on different lfda models [0.2 s]

══ Results ════════════════════════════════════════════════════════════════════════════════
Duration: 1.1 s

OK:       40
Failed:   0
Warnings: 0
Skipped:  0
```

**Comment by sctyner** [comment]
Just so I'm clear - the point of testing the plot method is to make sure it runs without error. Is that correct?

**Comment by terrytangyuan** [comment]
@sctyner Yes, I am not sure if there's a good way to test the rendered plots as far as I know. I think as long as the result from `lfda()` is correct, the rest should be straightforward usage of `rgl`.

**Comment by sctyner** [comment]
Ok. I know that [`vdiffr`](https://github.com/r-lib/vdiffr) is available to test the appearance of plots, but I've never seen it applied to 3D plots.
