### ISSUE TITLE
[JOSS review] - provide working examples

### ISSUE THREAD

**Issue by strengejacke** [terrytangyuan/lfda#28]
related to https://github.com/openjournals/joss-reviews/issues/1572

I can't quickly check if the package is working, because examples don't run. See, e.g., `?lfda`. The provided examples does not run. Please check your docs / examples and provide running examples for the user.

**Comment by sctyner** [comment]
@strengejacke were you able to get the plots on the README to render? I had issues which I assumed were due to my recent MacOS update, but this issue is making me reconsider.

**Comment by terrytangyuan** [comment]
I think this issue is only related to the examples in the roxygen docs where they are marked as `\dontrun` which is unintended. If so, I can fix them soon. The examples should be running fine.

**Comment by strengejacke** [comment]
I copy/pasted the example into the R console, so the code was executed, but failed.

**Comment by terrytangyuan** [comment]
Yes, since "trainData" variable does not exist yet in the examples. The examples were not meant to run successfully. It's only instructional and users are responsible for providing the data. Now that I re-think about it. I can for sure replace them with some running examples there.

**Comment by strengejacke** [comment]
> were you able to get the plots on the README to render?

Yes, that worked for me. It seems it requires RGL, which might cause issues on OSX. Maybe it's possible to replace with a plot-method that works on all OS?

**Comment by terrytangyuan** [comment]
Well `rgl` works for me on both MacOS and Windows. I really think that the `rgl` issue is not related to this package. Any package would possibly have issues with some versions of OS.
