### ISSUE TITLE
Update Gastrograph URL

### ISSUE THREAD

**Issue by dnpurdy** [terrytangyuan/lfda#31]
White paper URL has been updated to 

https://www.gastrograph.com/resources/local-fisher-discriminant-analysis-on-beer-style-clustering

**Comment by terrytangyuan** [comment]
Fixed https://github.com/terrytangyuan/lfda/commit/82c63244c438888a2c8fa04d6c74aa6777b708fd

**Comment by terrytangyuan** [comment]
**Note**: This package has been maintained by [@terrytangyuan](https://github.com/terrytangyuan) since 2015. Please [consider sponsoring](https://github.com/sponsors/terrytangyuan)!
