### ISSUE TITLE
Modify the structure of 3d visualization code

### ISSUE THREAD

**Issue by terrytangyuan** [terrytangyuan/lfda#5]
Make MetricTransformedViz() only for 3D visualization, instead of doing both lfda/klfda model building and then visualization. In other words, split the tasks.

**Comment by terrytangyuan** [comment]
@zachmayer I added unit test for the plotting but it looks like in Travis it cannot open the plotting device. Error: `RGL: unable to open X11 display`  in this build https://travis-ci.org/terrytangyuan/lfda/builds/75081008

Do you have any idea to get around with this?

**Comment by zachmayer** [comment]
https://cran.r-project.org/web/packages/rgl/index.html

Check the "system requirements" page:
`SystemRequirements:  OpenGL, GLU Library, zlib (optional), libpng (>=1.2.9, optional), FreeType (optional)`

You also need X11. You need to run something like this ([from the travis help page](http://docs.travis-ci.com/user/customizing-the-build/)):

``` yml
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq freeglut3-dev xorg openbox
```

`freeglut3-dev` will install openGL and GLU, the other 2 will install X11.

**Comment by zachmayer** [comment]
(btw, this is why we don't want caret to depend on rgl— it's a lot of effort to get installed)

**Comment by terrytangyuan** [comment]
Hmm I couldn't get it to work by adding `before_install` in Travis and `options(rgl.useNULL=TRUE)` in the plotting code. The code work fine by `devtools::test()` and `devtools::check()` though on my PC. Would this be enough for CRAN submission? Are they looking at my Travis build?

**Comment by zachmayer** [comment]
CRAN will be checking on a machine very much like the travis machine.  It won't have an rgl environment setup.
