### ISSUE TITLE
Before CRAN submission

### ISSUE THREAD

**Issue by terrytangyuan** [terrytangyuan/lfda#6]
@zachmayer  Do you know how long it takes for CRAN to review the package? Any suggestions before I submit?

**Comment by zachmayer** [comment]
I would strongly suggest going for 100% test coverage before you submit.  Other than that, if R CMD check passes with no errors and no warnings, you're probably good. 

Here's the submission process:
1. For new packages, briefly describe the package
2. For ANY and ALL R CMD NOTE's briefly explain why you think the note is ok to skip.

Run devtools::build_win() and make sure windows builds are working.  (They're email you a build log).

Note in your submission that you built on ubuntu (via travis's builds) and windows (via devtools::build_win()) and that both builds passed without errors or warnings.  (If either build has errors or warnings, you obviously need to fix them).

**Comment by zachmayer** [comment]
Also, the R Core team is very precise in their package requirements.  They may have feedback for you.  If they do, copy it here and I'll help you fix any issues.  Don't take it personally— these people have to deal with 100s of packages a day, so their emails are usually very terse!

Before your release, read this doc very closely: http://r-pkgs.had.co.nz/release.html

Then run `devtools::release()`!

**Comment by terrytangyuan** [comment]
Thanks! This is very helpful!

**Comment by terrytangyuan** [comment]
@zachmayer It looks like I am having this warning when `checking PDF version of manual ...`:

```
Warning: running command '"C:/PROGRA~1/R/R-32~1.1/bin/x64/Rcmd.exe" Rd2pdf  --batch --no-preview --build-dir="C:/Users/Yuan/AppData/Local/Temp/RtmpgFC4YU/Rd2pdf10d877e11598" --no-clean -o  lfda-manual.pdf  "C:/Users/Yuan/Desktop/lfda.Rcheck/lfda"' had status 1
 WARNING

LaTeX errors when creating PDF version.
This typically indicates Rd problems.
LaTeX errors found:
!pdfTeX error: pdflatex.EXE (file ts1-zi4r): Font ts1-zi4r at 600 not found
 ==> Fatal error occurred, no output PDF file produced!
```

But the logs from `devtools::build_win()` and from `Travis build` are both ok without this warning. Do you know what wen wrong? I've tried several solutions found online but didn't help.

**Comment by zachmayer** [comment]
You need to install latex on your local system to build the manual.  I suggest [mactex](http://tug.org/mactex/) for mac and [milktext](http://miktex.org/) for windows.

**Comment by terrytangyuan** [comment]
That's strange. I believe I have it installed very long ago. I write
technical papers in LaTex. Could you help me to check whether everything
went ok on Mac? Maybe I should also add Mac to the notes.

Also, how about the notes from Travis build saying something with the
CRAN-comments.md and CONDUCT.md? Are they ok? I learned those from your
caretEnsemble package.

**Comment by zachmayer** [comment]
add `CRAN-comments.md` and `CONDUCT.md` to [`.Rbuildignore`](https://github.com/terrytangyuan/lfda/blob/master/.Rbuildignore)

**Comment by zachmayer** [comment]
Maybe try the https://cran.r-project.org/bin/windows/Rtools/installer.html installer?

Perhaps R can't find your latex install.  I've never tried it on windows, so I'm not 100% sure.

**Comment by zachmayer** [comment]
I also wouldn't worry about it too much.  If your manual is built with roxygen2, you probably won't have any issues in it, unless you're trying to do something fancy.

**Comment by terrytangyuan** [comment]
Got it. Thanks. Could you run a check and test on Mac for me when you get a chance? I think adding that to cran-comments.md would be very helpful.

**Comment by zachmayer** [comment]
Sure.  I think you can have travis do mac builds as well.  I'll check though.

**Comment by zachmayer** [comment]
:+1: On the mac build.  No errors, warnings, or notes!

**Comment by terrytangyuan** [comment]
Awesome! Can you add that to cran-comments? Also help me check other things before I submit it to CRAN. Feel free to choose a spot to claim you are the contributor of this package!

**Comment by zachmayer** [comment]
You can just add it— you're the maintainer, they're your comments!  You can also add me as an author if you like (Zachary Deane-Mayer).

**Comment by zachmayer** [comment]
`devtools::release()` will release the package.  You'll need to respond to the confirmation email CRAN sends you.

**Comment by terrytangyuan** [comment]
@zachmayer Welcome to this new co-authorship! Let's work together to make this package better and publicize it! 

Before I release it, do you wanna check everything? Also, there are two NOTES in the most recent build [https://api.travis-ci.org/jobs/75188568/log.txt?deansi=true]. Could you check to see whether we need to write something for this in CRAN-COMMENTS? Please go ahead and make any changes you want. 

Once everything is set, I'll go ahead and release it.

**Comment by terrytangyuan** [comment]
@zachmayer [It is on CRAN now! ](https://cran.r-project.org/web/packages/lfda/) 

That was quick!

**Comment by zachmayer** [comment]
Congrats on your first CRAN package!  Now you can make a PR for caret to just use the `lfda` package for lfda models.  (And I think you should close your existing pr to add the 3d plot function)
